### ISSUE TITLE
Automatically build Jenkins and push to our rht-labs repo

### ISSUE THREAD

**Issue by springdo** [rht-labs/s2i-config-jenkins#35]
@ckavili  - we should treat this the same way as our `stack` for do500. We've historiaclly had times when Jenkins mirrors have flopped over.... 

FYI - @eformat / @philipdouble / @tylerauerbeck

**Comment by ckavili** [comment]
done https://github.com/rht-labs/s2i-config-jenkins/pull/37 :)
